// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBclEAHzOWhFKMRPDKuB_gevZUnrfMHbAU',
    appId: '1:536964929602:web:a303ebceeeddeb127c75db',
    messagingSenderId: '536964929602',
    projectId: 'pfe-flutter-75ff7',
    authDomain: 'pfe-flutter-75ff7.firebaseapp.com',
    storageBucket: 'pfe-flutter-75ff7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbAMKfzAsogW_xgqSAXE1gQ0h1oPZ71L0',
    appId: '1:536964929602:android:53c0bd5e31b2e2ea7c75db',
    messagingSenderId: '536964929602',
    projectId: 'pfe-flutter-75ff7',
    storageBucket: 'pfe-flutter-75ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDbOOFCSah_hLTYqs8yq3elzYPBr9XR5M',
    appId: '1:536964929602:ios:d0345399910792f67c75db',
    messagingSenderId: '536964929602',
    projectId: 'pfe-flutter-75ff7',
    storageBucket: 'pfe-flutter-75ff7.appspot.com',
    iosClientId: '536964929602-tbuh0bpijtbmajbffhd34jlcscjoi1sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDbOOFCSah_hLTYqs8yq3elzYPBr9XR5M',
    appId: '1:536964929602:ios:d0345399910792f67c75db',
    messagingSenderId: '536964929602',
    projectId: 'pfe-flutter-75ff7',
    storageBucket: 'pfe-flutter-75ff7.appspot.com',
    iosClientId: '536964929602-tbuh0bpijtbmajbffhd34jlcscjoi1sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPfe',
  );
}
